
CREATE TABLE [SRSDW].[CleansedAccount](
	[VIPOUTKey] [varchar](255) NULL,
	[XRefAcctKey] [varchar](255) NULL,
	[CurrentHASH] [varchar](255) NULL,
	[RECORDTYPE] [varchar](6) NULL,
	[DISTID] [varchar](14) NULL,
	[RSCUST] [varchar](25) NULL,
	[VPID#] [varchar](10) NULL,
	[VPDBA] [nvarchar](35) NULL,
	[VPLNAM] [nvarchar](35) NULL,
	[VPADDR] [nvarchar](35) NULL,
	[VPADDR2] [nvarchar](35) NULL,
	[VPCITY] [varchar](30) NULL,
	[VPSTAT] [varchar](2) NULL,
	[VPZIP9] [varchar](9) NULL,
	[VPCOUN] [varchar](30) NULL,
	[VPCTRY] [varchar](3) NULL,
	[VPPHON] [varchar](20) NULL,
	[VPCHN] [varchar](10) NULL,
	[VPSTORE] [varchar](10) NULL,
	[VPFRANIND] [varchar](1) NULL,
	[VPCSTS] [varchar](1) NULL,
	[VPIOCODE] [numeric](10, 0) NULL,
	[VPCOT] [varchar](2) NULL,
	[VPSUBCHNL] [varchar](2) NULL,
	[VPCUSTYP] [varchar](2) NULL,
	[VPPREM] [varchar](1) NULL,
	[VPSTATUS] [varchar](1) NULL,
	[VPMALT] [varchar](1) NULL,
	[VPWINE] [varchar](1) NULL,
	[VPSPIRITS] [varchar](1) NULL,
	[VPBUYGRP] [varchar](10) NULL,
	[VPLAT] [varchar](10) NULL,
	[VPLONG] [varchar](10) NULL,
	[VPFIPS] [varchar](5) NULL,
	[VPMSACD] [varchar](5) NULL,
	[VPFUTUR1] [varchar](20) NULL,
	[VPFUTUR2] [varchar](20) NULL,
	[VPOPEN] [varchar](8) NULL,
	[VPCLOSED] [varchar](8) NULL,
	[VPTRANSID] [varchar](10) NULL,
	[VPTRANSDT] [varchar](10) NULL,
	[VPOLDID] [varchar](10) NULL,
	[VPALTDIST] [varchar](20) NULL,
	[VPPARENT] [varchar](20) NULL,
	[VPLTLNCD] [varchar](2) NULL,
	[VPPBSLAT] [numeric](10, 6) NULL,
	[VPPBSLONG] [numeric](10, 6) NULL,
	[VPPBMCHCOD] [varchar](4) NULL,
	[VPPBLOCCOD] [varchar](4) NULL,
	[VPPBMCDESC] [varchar](120) NULL,
	[VPPBLCDESC] [varchar](120) NULL,
	[VPFIPS15] [numeric](15, 0) NULL,
	[VPDRAFT] [varchar](1) NULL,
	[TDLINXCD] [varchar](7) NULL,
	[VPSEAOPN] [numeric](2, 0) NULL,
	[VPSEACLS] [numeric](2, 0) NULL,
	[MAXABV] [varchar](128) NULL,
	[ROLLUPID] [varchar](128) NULL,
	[FILENAME] [varchar](100) NULL,
	[VIPValue_FIELDNAME] [varchar](100) NULL,
	[VOCOT] [varchar](100) NULL,
	[SRSRADVolume] [bigint] NULL,
	[SRSRADVolumeLast120Days] [bigint] NULL,
	[VOXRefAccounts] [bigint] NULL,
	[ActiveAccounts] [varchar](255) NULL,
	[ObjectiveFactMaxYears] [bigint] NULL,
	[ActivityFactMaxYears] [bigint] NULL,
	[SurveyFactMaxYears] [bigint] NULL,
	[ContactDim] [bigint] NULL,
	[AccountTeamDim] [bigint] NULL,
	[AccountsetDim] [bigint] NULL,
	[VIPOUTLastUpdated] [varchar](255) NULL,
	[VIPOUTNextAction] [varchar](255) NULL,
	[VIPOUTStatus] [varchar](255) NULL
) ON [PRIMARY]
GO


