CREATE TABLE [SRSDW].[DistributorValidation](
	SRSDistID [varchar](10) NOT NULL,
SRSAltDistID  [varchar](25) NOT NULL,
GVPAccountKey [varchar] (70) NULL,
GVPBDNId	 [varchar] (50)  NULL,
MatchDISTId	[varchar] (70) NULL,
SRSName		[NVARCHAR] (250)  NULL,
GVPName		[varchar](40) NOT NULL,
MatchName			  [varchar](30) NOT NULL,
SRSStreet			[NVARCHAR] (255)  NULL,
GVPBillingStreet	  [NVARCHAR] (255)  NULL,
GVPShippingStreet	   [NVARCHAR] (255)  NULL,
SRSCity				  [varchar](15) NOT NULL,
GVPBillingCity		   [NVARCHAR] (100)  NULL,
GVPShippingCity		  [NVARCHAR] (100)  NULL,
SRSState			  [varchar](2) NOT NULL,
GVPBillingState		  [NVARCHAR] (50)  NULL,
GVPShippingState	  [NVARCHAR] (50)  NULL,
MatchState			  [NVARCHAR](30),
SRSZip				  [NVARCHAR] (20)  NULL,
GVPBillingZip		  [NVARCHAR] (20)  NULL,
GVPShippingZip		  [NVARCHAR] (20)  NULL,
SRSPhone			  [varchar] (50)  NULL,
GVPPhone			  [varchar] (50)  NULL,
SRSRank				  DECIMAL(10,1) NULL,
GVPRank				  DECIMAL(10,1) NULL,
GVPCalculatedRank	  [varchar](30),
MatchRank			  [varchar](30),
SRSStatus			  [varchar] (25)  NULL,
GVPStatus			  [varchar] (25)  NULL,
MatchStatus			  [varchar](30),
DSREEMAIL			  [varchar](40) NOT NULL,
DSREP#				  [varchar](10)  NULL,
DSREPNAME			  [varchar](60)  NULL,
DSAREA				  [varchar](60)  NULL,
DSAREA#				  [varchar](10)  NULL,
DSCNT1				  [varchar](30) NOT NULL,
GVPPrimaryContact	  [NVARCHAR] (75)  NULL,
MatchPrimaryContact	  [varchar](30),
DSDIV#				  [varchar](10)  NULL,
DSDIVISION			 [varchar](60)  NULL,
DSEML1				  [varchar](60) NOT NULL,
DSISV				  [varchar](20) NOT NULL,
DSLSTAUDITDATE		  [varchar](10)  NULL,
DSLSTAUDITUSER		  [varchar](10)  NULL,
DSMARKET			  [varchar](60)  NULL,
DSMKT#				  [varchar](10)  NULL,
DSPHASE				  [varchar](1) NOT NULL,
FILENAME			  [varchar](100) NOT NULL,
SRSRADVolume		  [varchar](30),
SRSRADVolumeLast120Days [varchar](30),
CTLSum					[varchar](30),
CTLSSum					[varchar](30),
RADFactMaxYears			[varchar](30),
SRSDeplDAVolume			[varchar](30),
SRSDeplDAVolumeSMPeriod	[varchar](30)
) ON [PRIMARY]
GO


