CREATE TABLE SRSDW.[SRSCHAIN]
(
  RECORDTYPE    varchar(6)  NOT NULL,
  CHAIN         varchar(10) NOT NULL,
  [DESC]        varchar(50) NOT NULL,
  [DATEADDED]   [DATETIME] NOT NULL,
  [LASTUPDATED] [DATETIME] NOT NULL,
  [SOURCESTATUS] VARCHAR (10) NOT NULL,
	[SRSDWHash] varchar(32) null, 
  [FILENAME]     VARCHAR(100) NOT NULL 
  CONSTRAINT [PK_SRSCHAIN] PRIMARY KEY ([CHAIN])
)
