CREATE TABLE SRSDW.[SRSVALUE]
(
  RECORDTYPE  varchar(6)  NOT NULL,
  FIELD       varchar(10) NOT NULL,
  FIELDNAME   varchar(20) NOT NULL,
  CODE        varchar(3)  NOT NULL,
  [DESC]      varchar(50) NOT NULL,
  [DATEADDED] [DATETIME] NOT NULL,
  [LASTUPDATED] [DATETIME] NOT NULL,
  [SOURCESTATUS] VARCHAR (10) NOT NULL,
  [SRSDWHash] varchar(32) null, 
  [FILENAME] VARCHAR(100) NOT NULL,
	 CONSTRAINT [PK_SRSVALUE] PRIMARY KEY (FIELD,CODE)
)
