CREATE TABLE SRSDW.[VOOWNHIER]
(
	RECORDTYPE [varchar](6) NOT NULL,
	VPOCHNHCD1 Numeric(10) NOT NULL,
	VPOCHNHNM1 [varchar](35) NOT NULL,
	VPOCHNHCD2 Numeric(10)NULL,
	VPOCHNHNM2 Numeric(35)NULL,
	VPOCHNHCD3 Numeric(10)NULL,
	VPOCHNHNM3 [varchar](35)NULL,
	VPOCHNHCD4 Numeric(10) NOT NULL,
	VPOCHNHNM4 [varchar](35) NOT NULL,
	VPOCHNHSTAT Numeric(1)NULL,
	[DATEADDED] [DATETIME] NOT NULL,
	[LASTUPDATED] [DATETIME] NOT NULL,
	[SOURCESTATUS] VARCHAR (10) NOT NULL,
	[FILENAME] VARCHAR(100) NOT NULL
)
