CREATE TABLE [SRSDW].[VOXREF]
(
	RECORDTYPE [varchar](6) NOT NULL,
	DISTID [varchar](25) NOT NULL,
	RSCUST [varchar](25) NOT NULL,
	VPID# varchar(10) NOT NULL,
	VPST [varchar](2) NOT NULL,
	VPPARENT [varchar](25)NULL,
	TDLINXCD [varchar](7)NULL,
	[DATEADDED] [DATETIME] NOT NULL,
	[LASTUPDATED] [DATETIME] NOT NULL,
	[SOURCESTATUS] VARCHAR (10) NOT NULL,
	[FILENAME] VARCHAR(100) NOT NULL

)
