CREATE TABLE [GVP].[User] (
    [Id]                         CHAR (18)  NOT NULL,
    [UserName]                   NVARCHAR(75) NOT NULL,
    [LastName]                   NVARCHAR(50) NOT NULL,
    [FirstName]                  NVARCHAR(50) NULL,
    [Name]                       NVARCHAR(255) NOT NULL,
    [CompanyName]                NVARCHAR(80) NULL,
    [Division]                   NVARCHAR(80) NULL,
    [Department]                 NVARCHAR(90) NULL,
    [Title]                      NVARCHAR(100) NULL,
    [Street]                     NVARCHAR(235) NULL,
    [City]                       NVARCHAR(40) NULL,
    [State]                      NVARCHAR(30) NULL,
    [PostalCode]                 NVARCHAR(25) NULL,
    [Country]                    NVARCHAR(40) NULL,
    [Email]                      NVARCHAR(255) NULL,
    [Phone]                      VARCHAR (50) NULL,
    [Fax]                        VARCHAR (50) NULL,
    [MobilePhone]                Varchar(50) NULL,
    [Alias]                      NVARCHAR (25) NULL,
    [IsActive]                   NVARCHAR (255) NULL,
    [TimeZoneSidKey]             VARCHAR (35) NULL,
    [UserRoleId]                 CHAR (18) NULL,
    [LocaleSidKey]               NVARCHAR (255) NULL,
    [ProfileId]                  CHAR (18) NULL,
    [UserType]                   VARCHAR (20) NULL,
    [LanguageLocaleKey]          NVARCHAR (255) NULL,
    [EmployeeNumber]             NVARCHAR (255) NULL,
    [DelegatedApproverId]        CHAR (18) NULL,
    [ManagerId]                  VARCHAR (100) NULL,
    [LastLoginDate]              DATETIME NULL,
    [CreatedDate]                DATETIME NOT NULL,
    [CreatedById]                CHAR (18) NOT NULL,
    [LastModifiedDate]           DATETIME NOT NULL,
    [LastModifiedById]           CHAR (18) NOT NULL,
    [SystemModstamp]             DATETIME NOT NULL,
    [ForecastEnabled]            NVARCHAR (255) NOT NULL,
    [ContactId]                  CHAR (18) NULL,
    [AccountId]                  CHAR (18) NULL,
    [CallCenterId]               CHAR (18) NULL,
    [Extension]                  VARCHAR(20) NULL,
    [FederationIdentifier]       NVARCHAR (512) NULL,
    [gvp__End_of_Day__c]         NVARCHAR (255) NULL,
    [gvp__Geography_Key__c]      NVARCHAR (255) NULL,
    [gvp__GoodData_User_Type__c] NVARCHAR (255) NULL,
    [gvp__Start_of_Day__c]       NVARCHAR (255) NULL,
    [gvp__User_Key__c]           VARCHAR (100) NULL,
    [gvp__Custom_1__c]           NVARCHAR (255) NULL,
    [gvp__Custom_2__c]           NVARCHAR (255) NULL,
    [gvp__Custom_3__c]           NVARCHAR (255) NULL,
    [gvp__Custom_4__c]           NVARCHAR (255) NULL,
    [gvp__Custom_5__c]           NVARCHAR (255) NULL, 
    CONSTRAINT [PK_User] PRIMARY KEY ([Id])
);

