CREATE TABLE [GVW].[ContactDim](
    GVWContactSKey  int     identity(1,1),
	[ID] [VARCHAR](50) NOT NULL,
	[AccountID] [VARCHAR](50) NULL,
	[ActiveIndicator] [VARCHAR](50) NULL,
	[City] [VARCHAR](100) NULL,
	[Country] [NVARCHAR](50) NULL,
	[CreatedDate] [VARCHAR](50) NULL,
	[Custom1] [NVARCHAR](255) NULL,
	[Custom2] [NVARCHAR](255) NULL,
	[Custom3] [NVARCHAR](255) NULL,
	[Custom4] [NVARCHAR](255) NULL,
	[Custom5] [NVARCHAR](255) NULL,
	[CustomerExternalID] [VARCHAR](255) NULL,
	[Department] [NVARCHAR](255) NULL,
	[DoNotCall] [VARCHAR](50) NULL,
	[DoNotEmail] [VARCHAR](50) NULL,
	[EmailExternalID] [VARCHAR](255) NULL,
	[Email] [NVARCHAR](255) NULL,
	[Fax] [VARCHAR](50) NULL,
	[FirstName] [NVARCHAR](80) NULL,
	[FullName] [NVARCHAR](255) NULL,
	[Granularity] [VARCHAR](50) NULL,
	[HomePhone] [VARCHAR](50) NULL,
	[LastName] [NVARCHAR](80) NULL,
	[Level] [VARCHAR](255) NULL,
	[ManagerEmail] [NVARCHAR](255) NULL,
	[ManagerFirstName] [NVARCHAR](80) NULL,
	[ManagerFullName] [NVARCHAR](150) NULL,
	[ManagerID] [VARCHAR](50) NULL,
	[ManagerLastName] [NVARCHAR](80) NULL,
	[ManagerURL] [VARCHAR](255) NULL,
	[MobilePhone] [VARCHAR](50) NULL,
	[ModifiedDate] [VARCHAR](50) NULL,
	[OtherPhone] [VARCHAR](50) NULL,
	[OwnerEmail] [NVARCHAR](255) NULL,
	[OwnerFirstName] [NVARCHAR](80) NULL,
	[OwnerFullName] [NVARCHAR](150) NULL,
	[OwnerID] [VARCHAR](50) NULL,
	[OwnerLastName] [NVARCHAR](80) NULL,
	[OwnerURL] [VARCHAR](255) NULL,
	[Phone] [VARCHAR](50) NULL,
	[RecordType] [VARCHAR](50) NULL,
	[Role] [VARCHAR](255) NULL,
	[SalesmanExternalID] [NVARCHAR](255) NULL,
	[Salutation] [NVARCHAR](50) NULL,
	[SourceFile] [VARCHAR](255) NULL,
	[State] [NVARCHAR](50) NULL,
	[Street] [NVARCHAR](300) NULL,
	[Title] [NVARCHAR](255) NULL,
	[URL] [VARCHAR](255) NULL,
	[WorkEmail] [NVARCHAR](255) NULL,
	[WorkPhone] [VARCHAR](50) NULL,
	[Zip5] [VARCHAR](50) NULL, 
	[Zip] [VARCHAR](50) NULL,
  GVWCreatedDate  datetime default getdate() NOT NULL,
  GVWLastModifiedDate datetime default getdate() NOT NULL,
  GVWSourceID   int   default (0) NOT NULL,
  GVWDeleted    bit   default 0 NOT NULL,
    [GVWHash] VARCHAR(32) NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_ContactDim] PRIMARY KEY ([GVWContactSKey])
) ON [PRIMARY]
GO