CREATE TABLE [ERPIn].[AccountTeam](
	Account_Team_Key 	varchar(255) 	NOT NULL,
	Account_Key 		varchar(40) 	NOT NULL,
	Salesperson_Key 	varchar(255) 	NULL,
	Manager_1_Key 		varchar(255) 	NULL,
	Manager_2_Key 		varchar(255) 	NULL,
	Manager_3_Key 		varchar(255) 	NULL,
	Custom_1 			nvarchar(255) 	NULL,
	Custom_2 			nvarchar(255) 	NULL,
	Custom_3 			nvarchar(255) 	NULL,
	Custom_4 			nvarchar(255) 	NULL,
	Custom_5 			nvarchar(255) 	NULL,
	Sales_Division_Key	varchar(255) 	NOT NULL,
	Sales_Division_Name nvarchar(255) 	NOT NULL,
	Salesperson_Name 	nvarchar(255) 	NULL,
	Manager_1_Name 		nvarchar(255) 	NULL,
	Manager_2_Name 		nvarchar(255) 	NULL,
	Manager_3_Name 		nvarchar(255) 	NULL,
	Distributor_Key 	varchar(255) 	NULL,
	CONSTRAINT [PK_AccountTeam] PRIMARY KEY (Account_Team_Key)
     )