CREATE TABLE [ERPIn].[Invoice](
gvp__Account_Key__c				varchar(255) NOT NULL, 			
gvp__Action_Amount__c			money,
gvp__Action_Comments__c			varchar(255),
gvp__Action_Date__c				date  NULL,
gvp__Action_Reason__c			varchar(255),
gvp__Budget_Key__c				varchar(100),
gvp__Budget_Plan_Key__c			varchar(100),
gvp__Currency_Code__c			varchar(40),
gvp__Invoice_Amount__c			money,
gvp__Invoice_Balance__c			money,
gvp__Invoice_Date__c			date  NOT NULL,
gvp__Invoice_Number__c			varchar(255) NOT NULL,
gvp__User_Key__c				varchar(255),
gvp__Line_Item_Total__c			money,
gvp__Notes__c					varchar(255),
gvp__Payment_Method__c			varchar(100),
gvp__Posting_Date__c			date  NULL,
gvp__Program__c					varchar(255),
gvp__Program_Code__c			varchar(255),
gvp__Reason_for_Short_Pay__c	varchar(40),
RecordTypeId					varchar(255) NOT NULL,
gvp__Status__c					varchar(100),
gvp__Custom_Currency_1__c		money,
gvp__Custom_Currency_2__c		money,
gvp__Custom_Date_1__c			date  NULL,
gvp__Custom_Date_2__c			date  NULL,
gvp__Custom_Number_1__c			varchar(40),
gvp__Custom_Number_2__c			varchar(40),
gvp__Custom_Picklist_1__c		varchar(255),
gvp__Custom_Picklist_2__c		varchar(255),
gvp__Custom_Text_1__c			varchar(255),
gvp__Custom_Text_2__c			varchar(255),
gvp__Custom_Text_3__c			varchar(255),
gvp__Custom_Text_4__c			varchar(255),
gvp__Custom_Text_5__c			varchar(255)
CONSTRAINT [PK_Invoice] PRIMARY KEY (gvp__Invoice_Number__c)
)