CREATE TABLE ERPIn.[Product]
(
  Item_Number           varchar(255) not null, 
  Item_Name             nvarchar(80) not null,
  Label_Key             varchar(50) not null,
  Label_Name            nvarchar(80) not null,
  Varietal_Name         nvarchar(255),
  Product_Type          nvarchar(255),
  Product_Line          nvarchar(255),
  Brand_Key             varchar(255) not null,
  Brand_Name            nvarchar(80) not null,
  Brand_Ownership       varchar(255),
  Designation           nvarchar(255),
  Supplier_Key          varchar(255) not null,
  Supplier_Name         nvarchar(80) not null,
  Size_Key              varchar(255) not null,
  Size_Name             nvarchar(80) not null,
  Size_Volume           decimal(15,3) null,
  Units_per_Case        int not null,
  Vintage               nvarchar(255),
  Active_Flag           varchar(10),
  ABV                   decimal(4,2),
  Item_Key              varchar(255) not null,
  gvp__Custom_1__c      nvarchar(255),
  Package_Type          varchar(20) NOT NULL DEFAULT '',
  Container             varchar(20),
  Primary_Conversion    decimal(15,3),
  Secondary_Conversion  decimal(15,3),
  Label_Custom_1        nvarchar(255),
  Label_Custom_2        nvarchar(255),
  Item_Description      nvarchar(255),

    CONSTRAINT [PK_Product] PRIMARY KEY ([Item_Number]) 
 
)