CREATE TABLE [ERPIn].[Retailer]
(
	Transaction_Date            DATE          NOT NULL,
	Transaction_Type            CHAR(1)       NOT NULL,
	Transfer_Date               DATE          NULL,
	Active_Flag                 VARCHAR(25)   NULL,
	BDN_Id                      VARCHAR(40)   NULL,
	Chain_Banner_Name           NVARCHAR(255) NULL,
	Chain_HQ_1_Key              VARCHAR(100)  NULL,
	Chain_HQ_1_Name             NVARCHAR(255) NULL,
	Chain_HQ_2_Key              VARCHAR(100)  NULL,
	Chain_HQ_2_Name             NVARCHAR(255) NULL,
	Chain_HQ_3_Key              VARCHAR(100)  NULL,
	Chain_HQ_3_Name             NVARCHAR(255) NULL,
	Chain_HQ_4_Key              VARCHAR(100)  NULL,
	Chain_HQ_4_Name             NVARCHAR(255) NULL,
	Chain_Ind                   VARCHAR(255)  NULL,
	Chain_Marketing_Group_Code  VARCHAR(255)  NULL,
	Chain_Marketing_Group_Name  NVARCHAR(255) NULL,
	City                        NVARCHAR(40)  NULL,
	Close_Date                  DATE          NULL,
	Country                     NVARCHAR(50)  NULL,
	County_Name                 VARCHAR(50)   NULL,
	Dist_Acct_Number            NVARCHAR(40)  NULL,
	Distributor_Key             VARCHAR(255)  NULL,
	Fax                         VARCHAR(40)   NULL,
	FIPS_County_Code            VARCHAR(10)   NULL,
	FIPS_State_Code             VARCHAR(10)   NULL,
	Food_Type                   VARCHAR(255)  NULL,
	Franchise                   VARCHAR(50)   NULL,
	gvp__Custom_6__c            NVARCHAR(255) NULL, 
	Key_Account                 NVARCHAR(40)  NULL,
	Key_Account_1_Key           VARCHAR(40)   NULL,
	Key_Account_1_Name          NVARCHAR(255) NULL,
	Key_Account_2_Key           VARCHAR(40)   NULL,
	Key_Account_2_Name          NVARCHAR(255) NULL,
	Latitude                    DECIMAL(12,4) NULL,
	License_Number              VARCHAR(255)  NULL,
	Longitude                   DECIMAL(12,4) NULL,
	MSA_Code                    VARCHAR(4)    NULL,
	Open_Date                   DATE          NULL,
	Outlet_Number               VARCHAR(20)   NULL,
	[Owner]                     NVARCHAR(100) NULL,
	OwnerKey                    VARCHAR(255)  NULL,
	Phone                       VARCHAR(40)   NULL,
	Premise_Type                VARCHAR(80)   NOT NULL,
	Primary_Contact_Name        NVARCHAR(255) NULL,
	Primary_Ethnicity           VARCHAR(255)  NULL,
	Retailer_Ext_Key            VARCHAR(40)   NOT NULL,
	Retailer_Key                VARCHAR(255)  NOT NULL,
	Retailer_Name               NVARCHAR(255) NOT NULL,
	SourceFile                  VARCHAR(255)  NULL,
	[State]                     NVARCHAR(80)  NULL,
	Store_Volume                NVARCHAR(255) NULL,
	Street_1                    NVARCHAR(255) NULL,
	Street_2                    NVARCHAR(255) NULL, 
	Sub_Channel                 VARCHAR(255)  NULL,
	Territory_Key               VARCHAR(255)  NULL,
	Trade_Channel               NVARCHAR(255) NULL,
	Zip_Code                    NVARCHAR(20)  NULL,
	CONSTRAINT [PK_Retailer] PRIMARY KEY (Retailer_Key)
	)