CREATE TABLE [ERPIn].[Retailer]
(
	Transaction_Type            char(1)		  	 NOT NULL,
	Transaction_Date            date			 NOT NULL,
	Retailer_Key				VARCHAR (255) 	 NOT NULL,
	Retailer_Name				NVARCHAR (255)   NOT NULL,
	Street_1					nvarchar(255)	 NULL,
	Street_2		 			nvarchar(255)	 NULL,	
	City						NVARCHAR (40)	 NULL,
	State						NVARCHAR (20)    NULL,
	Zip_Code					NVARCHAR (20)    NULL,
	Country						NVARCHAR (50)    NULL,
	Phone						VARCHAR (50)     NULL,
	Fax							VARCHAR (50)     NULL,
	Shipping_Street_1 nvarchar(255) NULL,
	Shipping_Street_2 nvarchar(255) NULL, 
	Shipping_City NVARCHAR (100) NULL,
	Shipping_State NVARCHAR (50)    NULL,
	Shipping_Zip_Code NVARCHAR (20)    NULL,
	Shipping_Country NVARCHAR (40)    NULL,
	Distributor_Key				VARCHAR (255)    NULL,
	Dist_Acct_Number			NVARCHAR (40)    NULL,
	Territory_Key				VARCHAR (255)	 NOT NULL,
	Owner						NVARCHAR (80)    NULL,
	Key_Account					NVARCHAR (100)   NULL,
	Retailer_Ext_Key			VARCHAR (40)	 NOT NULL,
	Premise_Type				VARCHAR (80)	 NOT NULL,
	Chain_Ind					VARCHAR(255)	 NULL,
	Trade_Channel				NVARCHAR (255)	 NULL,
	Sub_Channel					NVARCHAR (255)   NULL,
	Food_Type					VARCHAR (255)	 NULL,
	License_Number				VARCHAR (255)	 NULL,
	Primary_Contact_Name		NVARCHAR (255)	 NULL,
	Active_Flag					VARCHAR (25)	 NULL,
	Chain_Banner_Name 			NVARCHAR (255)	 NULL,
	Chain_HQ_1_Key 				VARCHAR (40)	 NULL,
	Chain_HQ_1_Name				NVARCHAR (255)   NULL,
	Chain_HQ_2_Key 				VARCHAR (40)  	 NULL,
	Chain_HQ_2_Name 			NVARCHAR (255)   NULL,
	Chain_HQ_3_Key 				VARCHAR (40) 	 NULL,
	Chain_HQ_3_Name 			NVARCHAR (255)   NULL,
	Chain_HQ_4_Key 				VARCHAR (40) 	 NULL,
	Chain_HQ_4_Name 			NVARCHAR (255)   NULL,
	County_Name 				VARCHAR (50) 	 NULL,
	OwnerKey 					VARCHAR (255) 	 NULL,
	Key_Account_1_Key 			VARCHAR (40) 	 NULL,
	Key_Account_1_Name 			NVARCHAR (255)   NULL,
	Key_Account_2_Key			VARCHAR (40) 	 NULL,
	Key_Account_2_Name 			NVARCHAR (255)   NULL,
	FIPS_State_Code 			VARCHAR (10)	 NULL,
	FIPS_County_Code			VARCHAR (10)	 NULL,
	Primary_Ethnicity			VARCHAR (255) 	 NULL,
	Open_Date					DATE			 NULL,
	Close_Date					DATE			 NULL,
	Transfer_Date				DATE			 NULL,
	Chain_Marketing_Group_Code  VARCHAR (255) 	 NULL,
	Chain_Marketing_Group_Name  NVARCHAR (255)   NULL,
	Franchise					VARCHAR (10)	 NULL,
	Latitude					DECIMAL(12,4)    NULL,
	Longitude					DECIMAL(12,4)    NULL,
	MSA_Code					VARCHAR (4)	     NULL,
	Outlet_Number				VARCHAR (20)	 NULL,
	Store_Volume				NVARCHAR(255)	 NULL,
	Parent_Account              NVARCHAR(100) NULL,
	Customer_Priority           NVARCHAR(100) NULL,
	Territory                   VARCHAR(70) NULL,
	Status_Indicator            NVARCHAR(100) NULL,
	Primary_Email_Address       NVARCHAR(100) NULL,
	gvp__Custom_1__c               NVARCHAR(255) NULL,
	gvp__Custom_2__c                    NVARCHAR(255) NULL,
	gvp__Custom_3__c                    NVARCHAR(255) NULL,
	gvp__Custom_4__c                    NVARCHAR(255) NULL,
	gvp__Custom_5__c                    NVARCHAR(255) NULL,
	gvp__Custom_6__c            NVARCHAR(255)    NULL,
	gvp__Custom_7__c                    NVARCHAR(255) NULL,
	gvp__Custom_8__c                    NVARCHAR(255) NULL,
	gvp__Custom_9__c                    NVARCHAR(255) NULL,
	gvp__Custom_10__c                    NVARCHAR(255) NULL,
	BDN_Id                      VARCHAR (100)    NOT NULL, 
	SourceFile					VARCHAR(255)	 NULL,
	CONSTRAINT [PK_Retailer] PRIMARY KEY (Retailer_Key)
	)