CREATE TABLE [SRSIn].[CTLDA] (
    [RECORDTYPE] VARCHAR (6)   NOT NULL,
    [DISTID]     VARCHAR (8)   NOT NULL,
    [VIPSRS]     VARCHAR (5)   NOT NULL,
    [DISTNM]     VARCHAR (40)  NOT NULL,
    [CTITEM]     VARCHAR (30)  NOT NULL,
    [CTQTY]      NUMERIC (10)  NOT NULL,
    [CTUOM]      VARCHAR (1)   NOT NULL,
    [CTDATE]     VARCHAR (6)   NOT NULL,
    [CTPARENT]   VARCHAR (8)   NULL,
    [CTDISTITEM] VARCHAR (10)  NULL,
    [FILENAME]   VARCHAR (100) NOT NULL,
    [SEQID]      INT           IDENTITY (1, 1) NOT NULL
)