CREATE TABLE [SRSIn].[NONDA] (
    [DISTID]   VARCHAR (14)   NOT NULL,
    [DISTNM]   VARCHAR (30)  NOT NULL,
    [NODT]     VARCHAR (8)   NOT NULL,
    [INRANK]   VARCHAR (13)  NOT NULL,
    [FILENAME] VARCHAR (100) NOT NULL,
    [SEQID]    INT           IDENTITY (1, 1) NOT NULL
)