CREATE TABLE SRSIn.[SRSCHAIN]
(
  RECORDTYPE    varchar(6)  NOT NULL,
  CHAIN         varchar(10) NOT NULL,
  [DESC]        NVARCHAR(50) NOT NULL,
	[FILENAME] VARCHAR(100) NOT NULL ,
	[SEQID] [int] IDENTITY(1,1) NOT NULL
    CONSTRAINT [PK_SRSCHAIN] PRIMARY KEY ([CHAIN])
)
