CREATE TABLE [SRSIn].[SRSCHAIN] (
    [RECORDTYPE] VARCHAR (6)   NOT NULL,
    [CHAIN]      VARCHAR (10)  NOT NULL,
    [DESC]       NVARCHAR (50) NOT NULL,
    [FILENAME]   VARCHAR (100) NOT NULL,
    [SEQID]      INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_SRSCHAIN] PRIMARY KEY CLUSTERED ([CHAIN] ASC)
)
