CREATE TABLE [BevPathIn].[gvp__Shared_Account__c] (
    [gvp__BevPath_Connection__c]         VARCHAR (255) NULL,
    [gvp__Labels__c]                     VARCHAR (MAX) NULL,
    [gvp__Account__c]                    VARCHAR (255) NULL,
    [Fields]                             VARCHAR (255) NULL,
    [gvp__External_ID_Ref__c]            VARCHAR (255) NULL,
    [gvp__Account_Name__c]               VARCHAR (255) NULL,
    [gvp__DBA__c]                        VARCHAR (255) NULL,
    [gvp__Account_Full_Address__c]       VARCHAR (255) NULL,
    [gvp__Billing_Street__c]             VARCHAR (255) NULL,
    [gvp__Billing_City__c]               VARCHAR (255) NULL,
    [gvp__Billing_State__c]              VARCHAR (255) NULL,
    [gvp__Postal_Code__c]                VARCHAR (255) NULL,
    [gvp__Billing_County__c]             VARCHAR (255) NULL,
    [gvp__Region__c]                     VARCHAR (255) NULL,
    [gvp__Territory__c]                  VARCHAR (255) NULL,
    [gvp__Account_Segment__c]            VARCHAR (255) NULL,
    [gvp__PremiseType__c]                VARCHAR (255) NULL,
    [gvp__Distributor_Rep__c]            VARCHAR (255) NULL,
    [gvp__Distributor_Account_Number__c] VARCHAR (255) NULL,
    [gvp__Classification__c]             VARCHAR (255) NULL,
    [gvp__MSACode]                       VARCHAR (255) NULL,
    [gvp__ MSAName]                      VARCHAR (255) NULL,
    [gvp__Account_Key_List__c]           VARCHAR (MAX) NULL,
    [gvp__Account_Key__c]                VARCHAR (255) NULL,
    [gvp__Attribute_1__c]                VARCHAR (255) NULL,
    [gvp__Attribute_2__c]                VARCHAR (255) NULL,
    [gvp__Attribute_3__c]                VARCHAR (255) NULL,
    [gvp__Attribute_4__c]                VARCHAR (255) NULL,
    [gvp__Attribute_5__c]                VARCHAR (255) NULL,
    [gvp__Attribute_6__c]                VARCHAR (255) NULL,
    [gvp__Attribute_7__c]                VARCHAR (255) NULL,
    [gvp__Attribute_8__c]                VARCHAR (255) NULL,
    [gvp__Attribute_9__c]                VARCHAR (255) NULL,
    [gvp__Attribute_10__c]               VARCHAR (255) NULL
);
GO

