CREATE TABLE [dbo].[application_log](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LogType] [nvarchar](50) NOT NULL,
	[Message] [nvarchar](1000) NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_applicationlog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]